//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleniumAdvanced.accountsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerData", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CustomerData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LnameField;
        
        private long CellPhoneField;
        
        private decimal BalanceField;
        
        private int AccountNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Fname {
            get {
                return this.FnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FnameField, value) != true)) {
                    this.FnameField = value;
                    this.RaisePropertyChanged("Fname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Lname {
            get {
                return this.LnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LnameField, value) != true)) {
                    this.LnameField = value;
                    this.RaisePropertyChanged("Lname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public long CellPhone {
            get {
                return this.CellPhoneField;
            }
            set {
                if ((this.CellPhoneField.Equals(value) != true)) {
                    this.CellPhoneField = value;
                    this.RaisePropertyChanged("CellPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((this.AccountNumberField.Equals(value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="accountsService.CustomersServiceSoap")]
    public interface CustomersServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetCustomerByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomerById", ReplyAction="*")]
        SeleniumAdvanced.accountsService.GetCustomerByIdResponse GetCustomerById(SeleniumAdvanced.accountsService.GetCustomerByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomerById", ReplyAction="*")]
        System.Threading.Tasks.Task<SeleniumAdvanced.accountsService.GetCustomerByIdResponse> GetCustomerByIdAsync(SeleniumAdvanced.accountsService.GetCustomerByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerById", Namespace="http://tempuri.org/", Order=0)]
        public SeleniumAdvanced.accountsService.GetCustomerByIdRequestBody Body;
        
        public GetCustomerByIdRequest() {
        }
        
        public GetCustomerByIdRequest(SeleniumAdvanced.accountsService.GetCustomerByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCustomerByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetCustomerByIdRequestBody() {
        }
        
        public GetCustomerByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public SeleniumAdvanced.accountsService.GetCustomerByIdResponseBody Body;
        
        public GetCustomerByIdResponse() {
        }
        
        public GetCustomerByIdResponse(SeleniumAdvanced.accountsService.GetCustomerByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCustomerByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SeleniumAdvanced.accountsService.CustomerData GetCustomerByIdResult;
        
        public GetCustomerByIdResponseBody() {
        }
        
        public GetCustomerByIdResponseBody(SeleniumAdvanced.accountsService.CustomerData GetCustomerByIdResult) {
            this.GetCustomerByIdResult = GetCustomerByIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CustomersServiceSoapChannel : SeleniumAdvanced.accountsService.CustomersServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomersServiceSoapClient : System.ServiceModel.ClientBase<SeleniumAdvanced.accountsService.CustomersServiceSoap>, SeleniumAdvanced.accountsService.CustomersServiceSoap {
        
        public CustomersServiceSoapClient() {
        }
        
        public CustomersServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomersServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomersServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomersServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SeleniumAdvanced.accountsService.GetCustomerByIdResponse SeleniumAdvanced.accountsService.CustomersServiceSoap.GetCustomerById(SeleniumAdvanced.accountsService.GetCustomerByIdRequest request) {
            return base.Channel.GetCustomerById(request);
        }
        
        public SeleniumAdvanced.accountsService.CustomerData GetCustomerById(int id) {
            SeleniumAdvanced.accountsService.GetCustomerByIdRequest inValue = new SeleniumAdvanced.accountsService.GetCustomerByIdRequest();
            inValue.Body = new SeleniumAdvanced.accountsService.GetCustomerByIdRequestBody();
            inValue.Body.id = id;
            SeleniumAdvanced.accountsService.GetCustomerByIdResponse retVal = ((SeleniumAdvanced.accountsService.CustomersServiceSoap)(this)).GetCustomerById(inValue);
            return retVal.Body.GetCustomerByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SeleniumAdvanced.accountsService.GetCustomerByIdResponse> SeleniumAdvanced.accountsService.CustomersServiceSoap.GetCustomerByIdAsync(SeleniumAdvanced.accountsService.GetCustomerByIdRequest request) {
            return base.Channel.GetCustomerByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SeleniumAdvanced.accountsService.GetCustomerByIdResponse> GetCustomerByIdAsync(int id) {
            SeleniumAdvanced.accountsService.GetCustomerByIdRequest inValue = new SeleniumAdvanced.accountsService.GetCustomerByIdRequest();
            inValue.Body = new SeleniumAdvanced.accountsService.GetCustomerByIdRequestBody();
            inValue.Body.id = id;
            return ((SeleniumAdvanced.accountsService.CustomersServiceSoap)(this)).GetCustomerByIdAsync(inValue);
        }
    }
}
