//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transation
    {
        public int Tranid { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime TranDate { get; set; }
        public Nullable<int> TranAmount { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
